--------------------------------------------------------
--  File created - вівторок-серпня-11-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PINSUR_ANKT_A
--------------------------------------------------------

  CREATE TABLE "IKIS_ERSP"."PINSUR_ANKT_A" 
   (	"IAN_ID" NUMBER(14,0), 
	"IAN_IM" NUMBER(14,0), 
	"IAN_IC" NUMBER(2,0), 
	"IAN_NUMIDENT" VARCHAR2(12), 
	"IAN_INCODE" VARCHAR2(5), 
	"IAN_NAME1" VARCHAR2(500), 
	"IAN_PDT" NUMBER(14,0), 
	"IAN_NAME2" VARCHAR2(500), 
	"IAN_PDT_WHO" VARCHAR2(100), 
	"IAN_PDT_SERIA" VARCHAR2(5), 
	"IAN_TRUST_FIO" VARCHAR2(100), 
	"IAN_PDT_CODE" VARCHAR2(20), 
	"IAN_TRUST_ORG" VARCHAR2(100), 
	"IAN_PDT_DT" DATE, 
	"IAN_RO" NUMBER(14,0), 
	"IAN_TRUST_ADRESS" VARCHAR2(250), 
	"IAN_RO_CODE" VARCHAR2(25), 
	"IAN_TRUST_DRFO" VARCHAR2(10), 
	"IAN_TRUST_PHONE" VARCHAR2(20), 
	"IAN_RO_DT" DATE, 
	"REPL_TS" NUMBER(20,0) DEFAULT 0, 
	"REPL_TP" CHAR(1), 
	"IAN_RO_SERIA" VARCHAR2(25), 
	"IAN_SI_NO" VARCHAR2(20), 
	"IAN_MAIN_NUMIDENT" VARCHAR2(12), 
	"IAN_SI_DT" DATE, 
	"IAN_MAIN_INCODE" VARCHAR2(5), 
	"IAN_MAIN_NAME" VARCHAR2(250), 
	"IAN_MAIN_KOATUU" NUMBER(14,0), 
	"REPL_TSR" NUMBER, 
	"IAN_OBI_TS" NUMBER(20,0), 
	"IAN_SI_BEGIN_DT" DATE, 
	"IAN_SI_COMP_DT" DATE
   ) ;

   COMMENT ON COLUMN "IKIS_ERSP"."PINSUR_ANKT_A"."IAN_SI_BEGIN_DT" IS 'Дата початку терміну дії Договору';
   COMMENT ON COLUMN "IKIS_ERSP"."PINSUR_ANKT_A"."IAN_SI_COMP_DT" IS 'Дата завершення терміну дії Договору';
--------------------------------------------------------
--  DDL for Table PINSUR_ANKT_B
--------------------------------------------------------

  CREATE TABLE "IKIS_ERSP"."PINSUR_ANKT_B" 
   (	"IAB_ID" NUMBER(14,0), 
	"IAB_MN" NUMBER(14,0), 
	"IAB_KPF" NUMBER(3,0), 
	"IAB_TX" NUMBER(3,0), 
	"IAB_BS" NUMBER(14,0), 
	"IAB_IM" NUMBER(14,0), 
	"IAB_MIN" NUMBER(14,0), 
	"IAB_FNT" NUMBER(14,0), 
	"IAB_PF" NUMBER(14,0), 
	"IAB_RC" NUMBER(14,0), 
	"IAB_PROC_DECR" NUMBER(6,3), 
	"IAB_ISBENEFITS" CHAR(1), 
	"IAB_INVAL_ISREG" CHAR(1), 
	"IAB_INVAL_QNT" NUMBER(10,0), 
	"IAB_FMEMB_QNT" NUMBER(10,0), 
	"IAB_WORKER_QNT" NUMBER(10,0), 
	"IAB_STOP_DT" DATE, 
	"REPL_TS" NUMBER(20,0) DEFAULT 0, 
	"IAB_STOP_NAME" VARCHAR2(100), 
	"REPL_TP" CHAR(1), 
	"IAB_RS" NUMBER(14,0), 
	"IAB_STOP_NUM" VARCHAR2(20), 
	"REPL_TSR" NUMBER, 
	"IAB_OPF_CODE" NUMBER(20,0), 
	"IAB_OBI_TS" NUMBER(20,0), 
	"IAB_IS_BUDGET" VARCHAR2(10) DEFAULT 'F', 
	"IAB_IS_INVAL_ORG" VARCHAR2(10) DEFAULT 'F', 
	"IAB_IS_BOSS" VARCHAR2(10) DEFAULT 'F', 
	"IAB_PRAV_NUMIDENT" VARCHAR2(10)
   ) ;
--------------------------------------------------------
--  DDL for Table PINSUR_ANKT_C
--------------------------------------------------------

  CREATE TABLE "IKIS_ERSP"."PINSUR_ANKT_C" 
   (	"IAC_ID" NUMBER(14,0), 
	"IAC_IM" NUMBER(14,0), 
	"IAC_MDF" NUMBER(14,0) DEFAULT -1, 
	"IAC_STATE_REG_DT" DATE, 
	"IAC_RU" NUMBER(14,0) DEFAULT 0, 
	"IAC_IS_SHIPBUILD" CHAR(1) DEFAULT 'F', 
	"IAC_IS_DELF" CHAR(1) DEFAULT 'F', 
	"IAC_IS_PAYER" CHAR(1) DEFAULT 'F', 
	"IAC_CTRL_EDRPOU" VARCHAR2(10), 
	"IAC_CTRL_NAME" VARCHAR2(250), 
	"IAC_MRD" NUMBER(14,0), 
	"IAC_VOL_CONTR_START_DT" DATE, 
	"IAC_VOL_CONTR_STOP_DT" DATE, 
	"IAC_VOL_CONTR_BREAK_DT" DATE, 
	"IAC_RB" NUMBER(14,0) DEFAULT 0, 
	"IAC_LIQ_COURT_NAME" VARCHAR2(200), 
	"IAC_LIQ_COURT_SENT_NUM" VARCHAR2(100), 
	"IAC_LIQ_COURT_SENT_DT" DATE, 
	"IAC_LIQ_COURT_SENT_LAW_DT" DATE, 
	"IAC_LIQ_CRED_TERM_DT" DATE, 
	"IAC_LIQ_ACT_NUM" VARCHAR2(25), 
	"IAC_LIQ_ACT_DT" DATE, 
	"IAC_LIQ_COMM_DT" DATE, 
	"IAC_LIQ_COMM_HEAD_PASS" VARCHAR2(10), 
	"IAC_LIQ_COMM_HEAD_SURNAME" VARCHAR2(70), 
	"IAC_LIQ_COMM_HEAD_NAME" VARCHAR2(150), 
	"IAC_LIQ_COMM_LOCATION" VARCHAR2(150), 
	"IAC_LIQ_MANAGER_PASS" VARCHAR2(10), 
	"IAC_LIQ_MANAGER_SURNAME" VARCHAR2(70), 
	"IAC_LIQ_MANAGER_NAME" VARCHAR2(150), 
	"IAC_MRDS" NUMBER(14,0), 
	"IAC_RECORD_NUM" NUMBER(10,0), 
	"IAC_MRS" NUMBER(14,0) DEFAULT 0, 
	"REPL_TS" NUMBER(20,0) DEFAULT 0, 
	"REPL_TP" CHAR(1), 
	"REPL_TSR" NUMBER, 
	"IAC_OBI_TS" NUMBER(20,0), 
	"IAC_VI" NUMBER(14,0) DEFAULT 0, 
	"IAC_PUBLIC_DT" DATE, 
	"IAC_STATE_REG_TERM_DT" DATE, 
	"IAC_IS_NPD" VARCHAR2(1)
   ) ;

   COMMENT ON COLUMN "IKIS_ERSP"."PINSUR_ANKT_C"."IAC_IS_NPD" IS 'Ознака ФОП одночасно проводить незалежну професійну діяльність';
--------------------------------------------------------
--  DDL for Table PINSUR_CHNG_DOC
--------------------------------------------------------

  CREATE TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" 
   (	"IH_ID" NUMBER(14,0), 
	"IH_IM" NUMBER(14,0), 
	"IH_IVH" NUMBER(14,0), 
	"IH_ORG" NUMBER(5,0), 
	"IH_DS" NUMBER(14,0), 
	"IH_ITH" NUMBER(14,0), 
	"IH_IAN" NUMBER(14,0), 
	"IH_IAB" NUMBER(14,0), 
	"IH_IAH" NUMBER(14,0), 
	"REPL_PACK" NUMBER(10,0), 
	"IH_IXH" NUMBER(14,0), 
	"IH_IKH" NUMBER(14,0), 
	"IH_IPH" NUMBER(14,0), 
	"IH_TP" CHAR(1), 
	"IH_NAME" VARCHAR2(250), 
	"IH_CREATE_DT" DATE, 
	"IH_REG_DT" DATE, 
	"REPL_TS" NUMBER(20,0) DEFAULT 0, 
	"IH_WRITER" VARCHAR2(60), 
	"IH_REF_CHNG" RAW(2), 
	"IH_FILE" NUMBER(14,0), 
	"REPL_TP" CHAR(1), 
	"IH_FILE_OZSZ" NUMBER(14,0), 
	"IH_ATTR_CHNG" RAW(8), 
	"IH_START_DT" DATE, 
	"IH_ST" VARCHAR2(10), 
	"IH_STOP_DT" DATE, 
	"IH_ST_ACTUAL" VARCHAR2(10), 
	"IH_ST_CNTRL" VARCHAR2(10), 
	"IH_ST_CNTRL_E" VARCHAR2(10), 
	"REPL_TS_CENTER" NUMBER(20,0) DEFAULT 0, 
	"REPL_SEANS_DOC" NUMBER, 
	"REPL_SEANS_ST" NUMBER, 
	"IH_DS_FIRST" NUMBER(14,0), 
	"IH_EDR_ID" NUMBER(20,0), 
	"REPL_TSR" NUMBER, 
	"IH_USR_ACT" NUMBER(14,0), 
	"IH_OBI_TS" NUMBER(20,0), 
	"IH_IAC" NUMBER(14,0)
   ) ;
--------------------------------------------------------
--  DDL for Table PINSUR_MAIN
--------------------------------------------------------

  CREATE TABLE "IKIS_ERSP"."PINSUR_MAIN" 
   (	"IM_ID" NUMBER(14,0), 
	"IM_IH" NUMBER(14,0), 
	"IM_CODE_PSV" VARCHAR2(21), 
	"IM_IH_PRIOR" NUMBER(14,0), 
	"IM_DT_PSV" DATE, 
	"IM_ST" CHAR(1), 
	"REPL_TS" NUMBER(20,0) DEFAULT 0, 
	"IM_TS" NUMBER(20,0) DEFAULT 0, 
	"REPL_TP" CHAR(1), 
	"IM_ID_SPOV" NUMBER(14,0), 
	"IM_INSPECTOR" VARCHAR2(100), 
	"IM_ID_OZSZ" NUMBER(14,0), 
	"IM_CL_SRC" VARCHAR2(10), 
	"REPL_SEANS" NUMBER, 
	"IM_GUID" NUMBER(14,0), 
	"IM_GUID_EDR" NUMBER(14,0), 
	"REPL_TSR" NUMBER, 
	"IM_OBI_TS" NUMBER(20,0)
   )  ENABLE ROW MOVEMENT ;
--------------------------------------------------------
--  DDL for Table PINSUR_KVED
--------------------------------------------------------

  CREATE TABLE "IKIS_ERSP"."PINSUR_KVED" 
   (	"IV_ID" NUMBER(14,0), 
	"IV_KVD" NUMBER(14,0), 
	"IV_IVH" NUMBER(14,0), 
	"IV_TP" VARCHAR2(10), 
	"REPL_TS" NUMBER(20,0) DEFAULT 0, 
	"REPL_TP" CHAR(1), 
	"REPL_TSR" NUMBER, 
	"IV_OBI_TS" NUMBER(20,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NSI_KVED
--------------------------------------------------------

  CREATE TABLE "IKIS_NDI"."NSI_KVED" 
   (	"KVD_ID" NUMBER(14,0), 
	"KVD_SECTION" CHAR(1), 
	"KVD_SUBSECTION" CHAR(1), 
	"KVD_PARTITION" CHAR(2), 
	"KVD_GROUP" CHAR(1), 
	"KVD_CLASS" CHAR(1), 
	"KVD_SUBCLASS" CHAR(1), 
	"KVD_NAME" VARCHAR2(250), 
	"KVD_KVD" NUMBER(14,0), 
	"KVD_ST" CHAR(1), 
	"KVD_SNAME" VARCHAR2(100), 
	"KVD_DEL_DT" DATE, 
	"REPL_PACK" NUMBER(14,0), 
	"REPL_TP" VARCHAR2(1), 
	"REPL_TS" NUMBER(20,0) DEFAULT 0, 
	"KVD_TYPE" VARCHAR2(10)
   ) 
   CACHE ;
--------------------------------------------------------
--  DDL for Table NSI_REGION_UKR
--------------------------------------------------------

  CREATE TABLE "IKIS_NDI"."NSI_REGION_UKR" 
   (	"RU_ID" NUMBER(14,0), 
	"RU_CODE" VARCHAR2(3), 
	"RU_NAME" VARCHAR2(100), 
	"RU_SNAME" VARCHAR2(100), 
	"RU_ST" CHAR(1) DEFAULT 'A', 
	"RU_CODE2" NUMBER(5,0)
   ) ;
--------------------------------------------------------
--  DDL for Table NSI_INSURERCAT
--------------------------------------------------------

  CREATE TABLE "IKIS_NDI"."NSI_INSURERCAT" 
   (	"IC_ID" NUMBER(2,0), 
	"IC_NAME" VARCHAR2(250), 
	"IC_IC" NUMBER(2,0), 
	"IC_UF_TP" CHAR(1) DEFAULT 'U', 
	"IC_HR_TP" CHAR(1), 
	"IC_SNAME" VARCHAR2(150), 
	"IC_ST" CHAR(1), 
	"IC_CODE" VARCHAR2(10), 
	"IC_NOTE" VARCHAR2(2000), 
	"IC_DEL_DT" DATE, 
	"REPL_PACK" NUMBER(10,0), 
	"REPL_TP" VARCHAR2(1), 
	"REPL_TS" NUMBER(20,0) DEFAULT 0, 
	"IC_NAME_PORTAL" VARCHAR2(500)
   ) ;

   COMMENT ON COLUMN "IKIS_NDI"."NSI_INSURERCAT"."IC_NAME_PORTAL" IS 'Назва для порталу';
--------------------------------------------------------
--  Constraints for Table PINSUR_ANKT_A
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" ADD CONSTRAINT "IPK_INSUR_ANKT_A" PRIMARY KEY ("IAN_ID")
  USING INDEX "IKIS_ERSP"."IPK_INSUR_ANKT_A"  ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" MODIFY ("IAN_ID" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" MODIFY ("IAN_IM" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" MODIFY ("IAN_IC" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" MODIFY ("IAN_PDT" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" MODIFY ("IAN_RO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PINSUR_ANKT_B
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "CHK_PINSUR_ANKT_B_IAB_IS_BOSS" CHECK (IAB_IS_BOSS in ('T','F')) ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "CHK_PINSUR_ANKT_B_IAB_IS_BUDGE" CHECK (IAB_IS_BUDGET in ('T','F')) ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "CHK_PINSUR_ANKT_B_IAB_IS_INVAL" CHECK (IAB_IS_INVAL_ORG in ('T','F')) ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "IPK_INSUR_ANKT_B" PRIMARY KEY ("IAB_ID")
  USING INDEX "IKIS_ERSP"."IPK_INSUR_ANKT_B"  ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_ID" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_MN" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_BS" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_IM" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_MIN" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_FNT" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_PF" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_RC" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_ISBENEFITS" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_INVAL_ISREG" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" MODIFY ("IAB_RS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PINSUR_ANKT_C
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" MODIFY ("IAC_ID" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" MODIFY ("IAC_IM" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" MODIFY ("IAC_MDF" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" MODIFY ("IAC_RU" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" MODIFY ("IAC_IS_SHIPBUILD" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" MODIFY ("IAC_IS_DELF" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" MODIFY ("IAC_IS_PAYER" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" MODIFY ("IAC_RB" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" MODIFY ("IAC_MRS" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" MODIFY ("IAC_VI" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" ADD CONSTRAINT "XPK_PINSUR_ANKT_C" PRIMARY KEY ("IAC_ID")
  USING INDEX "IKIS_ERSP"."XPK_PINSUR_ANKT_C"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PINSUR_CHNG_DOC
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "IPK_INSUR_CHNG_DOC" PRIMARY KEY ("IH_ID")
  USING INDEX "IKIS_ERSP"."IPK_INSUR_CHNG_DOC"  ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_ID" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_IM" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_ORG" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_DS" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_ITH" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_IAN" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_IAB" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_IAH" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_IXH" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_IKH" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_IPH" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_TP" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_ST_CNTRL" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" MODIFY ("IH_ST_CNTRL_E" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PINSUR_MAIN
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_MAIN" ADD CONSTRAINT "IPK_INSUR_MAIN" PRIMARY KEY ("IM_ID")
  USING INDEX "IKIS_ERSP"."IPK_INSUR_MAIN"  ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_MAIN" MODIFY ("IM_ID" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_MAIN" MODIFY ("IM_GUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PINSUR_KVED
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_KVED" MODIFY ("IV_ID" NOT NULL ENABLE);
  ALTER TABLE "IKIS_ERSP"."PINSUR_KVED" ADD CONSTRAINT "XPK_PINSUR_KVED" PRIMARY KEY ("IV_ID")
  USING INDEX "IKIS_ERSP"."XPK_PINSUR_KVED"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NSI_KVED
--------------------------------------------------------

  ALTER TABLE "IKIS_NDI"."NSI_KVED" ADD CONSTRAINT "IPK_NSI_KVED" PRIMARY KEY ("KVD_ID")
  USING INDEX "IKIS_NDI"."IPK_NSI_KVED"  ENABLE;
  ALTER TABLE "IKIS_NDI"."NSI_KVED" MODIFY ("KVD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NSI_REGION_UKR
--------------------------------------------------------

  ALTER TABLE "IKIS_NDI"."NSI_REGION_UKR" MODIFY ("RU_ID" NOT NULL ENABLE);
  ALTER TABLE "IKIS_NDI"."NSI_REGION_UKR" ADD CONSTRAINT "XPK_NSI_REGION_UKR" PRIMARY KEY ("RU_ID")
  USING INDEX "IKIS_NDI"."XPK_NSI_REGION_UKR"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NSI_INSURERCAT
--------------------------------------------------------

  ALTER TABLE "IKIS_NDI"."NSI_INSURERCAT" ADD CONSTRAINT "CHK_NSI_INSURERCAT_IC_UF_TP" CHECK (IC_UF_TP in ('U','F')) ENABLE;
  ALTER TABLE "IKIS_NDI"."NSI_INSURERCAT" ADD CONSTRAINT "IPK_INSURERCAT" PRIMARY KEY ("IC_ID")
  USING INDEX "IKIS_NDI"."IPK_INSURERCAT"  ENABLE;
  ALTER TABLE "IKIS_NDI"."NSI_INSURERCAT" ADD CONSTRAINT "REGISTERTYPES62" CHECK (ic_uf_tp IN('U','F')) ENABLE;
  ALTER TABLE "IKIS_NDI"."NSI_INSURERCAT" MODIFY ("IC_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PINSUR_ANKT_A
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" ADD CONSTRAINT "FK_IAN_IC" FOREIGN KEY ("IAN_IC")
	  REFERENCES "IKIS_NDI"."NSI_INSURERCAT" ("IC_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" ADD CONSTRAINT "FK_IAN_IM" FOREIGN KEY ("IAN_IM")
	  REFERENCES "IKIS_ERSP"."PINSUR_MAIN" ("IM_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" ADD CONSTRAINT "FK_IAN_MAIN_KOATUU" FOREIGN KEY ("IAN_MAIN_KOATUU")
	  REFERENCES "IKIS_NDI"."NSI_KOATUU" ("KT_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" ADD CONSTRAINT "FK_IAN_PDT" FOREIGN KEY ("IAN_PDT")
	  REFERENCES "IKIS_NDI"."NSI_PRSN_DOCTP" ("PDT_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_A" ADD CONSTRAINT "FK_IAN_RO" FOREIGN KEY ("IAN_RO")
	  REFERENCES "IKIS_NDI"."NSI_REG_ORG" ("RO_ID") DEFERRABLE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PINSUR_ANKT_B
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_IAB_BS" FOREIGN KEY ("IAB_BS")
	  REFERENCES "IKIS_NDI"."NSI_BUSINESS_ST" ("BS_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_IAB_FNT" FOREIGN KEY ("IAB_FNT")
	  REFERENCES "IKIS_NDI"."NSI_FIN_TP" ("FNT_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_IAB_IM" FOREIGN KEY ("IAB_IM")
	  REFERENCES "IKIS_ERSP"."PINSUR_MAIN" ("IM_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_IAB_KPF" FOREIGN KEY ("IAB_KPF")
	  REFERENCES "IKIS_NDI"."NSI_KOPFG" ("KPF_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_IAB_MIN" FOREIGN KEY ("IAB_MIN")
	  REFERENCES "IKIS_NDI"."NSI_MINISTRY" ("MIN_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_IAB_MN" FOREIGN KEY ("IAB_MN")
	  REFERENCES "IKIS_NDI"."NSI_MNG_FORM" ("MN_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_IAB_PF" FOREIGN KEY ("IAB_PF")
	  REFERENCES "IKIS_NDI"."NSI_PROP_FORM" ("PF_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_IAB_RC" FOREIGN KEY ("IAB_RC")
	  REFERENCES "IKIS_NDI"."NSI_RISK_CODE" ("RC_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_IAB_RS" FOREIGN KEY ("IAB_RS")
	  REFERENCES "IKIS_NDI"."NSI_REASON_STOP" ("RS_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_IAB_TX" FOREIGN KEY ("IAB_TX")
	  REFERENCES "IKIS_NDI"."NSI_TAXATION" ("TX_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_B" ADD CONSTRAINT "FK_PIAB_OPF_CODE" FOREIGN KEY ("IAB_OPF_CODE")
	  REFERENCES "IKIS_NDI"."NSI_OPF_CODE" ("OPF_KD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PINSUR_ANKT_C
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" ADD CONSTRAINT "FK_IAC_IM" FOREIGN KEY ("IAC_IM")
	  REFERENCES "IKIS_ERSP"."PINSUR_MAIN" ("IM_ID") ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" ADD CONSTRAINT "FK_IAC_MDF_DEFERRABLE" FOREIGN KEY ("IAC_MDF")
	  REFERENCES "IKIS_NDI"."NSI_DICT_MODIF" ("ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" ADD CONSTRAINT "FK_IAC_MRD_DEFERRABLE" FOREIGN KEY ("IAC_MRD")
	  REFERENCES "IKIS_SYS"."MRDORG" ("MRD_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" ADD CONSTRAINT "FK_IAC_MRS" FOREIGN KEY ("IAC_MRS")
	  REFERENCES "IKIS_NDI"."NSI_MRD_REASON_STOP" ("MRS_ID") ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" ADD CONSTRAINT "FK_IAC_RB_DEFERRABLE" FOREIGN KEY ("IAC_RB")
	  REFERENCES "IKIS_NDI"."NSI_REASON_BREAK" ("RB_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" ADD CONSTRAINT "FK_IAC_RU" FOREIGN KEY ("IAC_RU")
	  REFERENCES "IKIS_NDI"."NSI_REGION_UKR" ("RU_ID") ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_ANKT_C" ADD CONSTRAINT "FK_IAC_VI" FOREIGN KEY ("IAC_VI")
	  REFERENCES "IKIS_NDI"."NSI_VOL_INSURER" ("VI_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PINSUR_CHNG_DOC
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_IH_DS" FOREIGN KEY ("IH_DS")
	  REFERENCES "IKIS_NDI"."NSI_DATA_SOURCE" ("DS_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_IH_IAC_DEFERRABLE" FOREIGN KEY ("IH_IAC")
	  REFERENCES "IKIS_ERSP"."PINSUR_ANKT_C" ("IAC_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_IH_ORG" FOREIGN KEY ("IH_ORG")
	  REFERENCES "IKIS_SYS"."OPFU" ("ORG_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PFILE" FOREIGN KEY ("IH_FILE")
	  REFERENCES "IKIS_ERS"."INSUR_FILE" ("FILE_ID") ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PFILE_OZSZ" FOREIGN KEY ("IH_FILE_OZSZ")
	  REFERENCES "IKIS_ERS"."INSUR_FILE" ("FILE_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_IAB" FOREIGN KEY ("IH_IAB")
	  REFERENCES "IKIS_ERSP"."PINSUR_ANKT_B" ("IAB_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_IAH" FOREIGN KEY ("IH_IAH")
	  REFERENCES "IKIS_ERSP"."PINSUR_ADR_HST" ("IAH_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_IAN" FOREIGN KEY ("IH_IAN")
	  REFERENCES "IKIS_ERSP"."PINSUR_ANKT_A" ("IAN_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_IKH" FOREIGN KEY ("IH_IKH")
	  REFERENCES "IKIS_ERSP"."PINSUR_CONT_HST" ("IKH_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_IM" FOREIGN KEY ("IH_IM")
	  REFERENCES "IKIS_ERSP"."PINSUR_MAIN" ("IM_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_IPH" FOREIGN KEY ("IH_IPH")
	  REFERENCES "IKIS_ERSP"."PINSUR_BNKPAY_HST" ("IPH_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_ITH" FOREIGN KEY ("IH_ITH")
	  REFERENCES "IKIS_ERSP"."PINSUR_TAXTP_HST" ("ITH_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_IVH" FOREIGN KEY ("IH_IVH")
	  REFERENCES "IKIS_ERSP"."PINSUR_KVED_HST" ("IVH_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_IXH" FOREIGN KEY ("IH_IXH")
	  REFERENCES "IKIS_ERSP"."PINSUR_BNKACC_HST" ("IXH_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_ST_CNTRL" FOREIGN KEY ("IH_ST_CNTRL")
	  REFERENCES "IKIS_ERSP"."PINSUR_DUAL" ("DUMMY") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_ST_CNTRL_E" FOREIGN KEY ("IH_ST_CNTRL_E")
	  REFERENCES "IKIS_ERSP"."PINSUR_DUAL" ("DUMMY") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_CHNG_DOC" ADD CONSTRAINT "FK_PIH_USR_ACT" FOREIGN KEY ("IH_USR_ACT")
	  REFERENCES "IKIS_SYSWEB"."W_USERS" ("WU_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PINSUR_MAIN
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_MAIN" ADD CONSTRAINT "FK_IM_IH_PRIOR" FOREIGN KEY ("IM_IH_PRIOR")
	  REFERENCES "IKIS_ERSP"."PINSUR_CHNG_DOC" ("IH_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_MAIN" ADD CONSTRAINT "FK_PIM_IH" FOREIGN KEY ("IM_IH")
	  REFERENCES "IKIS_ERSP"."PINSUR_CHNG_DOC" ("IH_ID") DEFERRABLE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PINSUR_KVED
--------------------------------------------------------

  ALTER TABLE "IKIS_ERSP"."PINSUR_KVED" ADD CONSTRAINT "FK_IV_IVH" FOREIGN KEY ("IV_IVH")
	  REFERENCES "IKIS_ERSP"."PINSUR_KVED_HST" ("IVH_ID") DEFERRABLE ENABLE;
  ALTER TABLE "IKIS_ERSP"."PINSUR_KVED" ADD CONSTRAINT "FK_IV_KVD" FOREIGN KEY ("IV_KVD")
	  REFERENCES "IKIS_NDI"."NSI_KVED" ("KVD_ID") DEFERRABLE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NSI_KVED
--------------------------------------------------------

  ALTER TABLE "IKIS_NDI"."NSI_KVED" ADD CONSTRAINT "FK_KVD_KVD" FOREIGN KEY ("KVD_KVD")
	  REFERENCES "IKIS_NDI"."NSI_KVED" ("KVD_ID") DEFERRABLE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NSI_INSURERCAT
--------------------------------------------------------

  ALTER TABLE "IKIS_NDI"."NSI_INSURERCAT" ADD CONSTRAINT "FK_IC_IC" FOREIGN KEY ("IC_IC")
	  REFERENCES "IKIS_NDI"."NSI_INSURERCAT" ("IC_ID") DEFERRABLE ENABLE;
